package njsyg.greendao.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import njsyg.greendao.db.model.DB_Device;
import njsyg.greendao.db.model.DB_HomeServer;
import njsyg.greendao.db.model.DB_HServerKey;
import njsyg.greendao.db.model.DB_HServerAndUser;
import njsyg.greendao.db.model.DB_User;
import njsyg.greendao.db.model.DB_HServerOnlineRecord;
import njsyg.greendao.db.model.DB_DeviceOnlineRecord;
import njsyg.greendao.db.model.DB_DeviceRealData;
import njsyg.greendao.db.model.DB_DeviceHisData;

import njsyg.greendao.db.dao.DB_DeviceDao;
import njsyg.greendao.db.dao.DB_HomeServerDao;
import njsyg.greendao.db.dao.DB_HServerKeyDao;
import njsyg.greendao.db.dao.DB_HServerAndUserDao;
import njsyg.greendao.db.dao.DB_UserDao;
import njsyg.greendao.db.dao.DB_HServerOnlineRecordDao;
import njsyg.greendao.db.dao.DB_DeviceOnlineRecordDao;
import njsyg.greendao.db.dao.DB_DeviceRealDataDao;
import njsyg.greendao.db.dao.DB_DeviceHisDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dB_DeviceDaoConfig;
    private final DaoConfig dB_HomeServerDaoConfig;
    private final DaoConfig dB_HServerKeyDaoConfig;
    private final DaoConfig dB_HServerAndUserDaoConfig;
    private final DaoConfig dB_UserDaoConfig;
    private final DaoConfig dB_HServerOnlineRecordDaoConfig;
    private final DaoConfig dB_DeviceOnlineRecordDaoConfig;
    private final DaoConfig dB_DeviceRealDataDaoConfig;
    private final DaoConfig dB_DeviceHisDataDaoConfig;

    private final DB_DeviceDao dB_DeviceDao;
    private final DB_HomeServerDao dB_HomeServerDao;
    private final DB_HServerKeyDao dB_HServerKeyDao;
    private final DB_HServerAndUserDao dB_HServerAndUserDao;
    private final DB_UserDao dB_UserDao;
    private final DB_HServerOnlineRecordDao dB_HServerOnlineRecordDao;
    private final DB_DeviceOnlineRecordDao dB_DeviceOnlineRecordDao;
    private final DB_DeviceRealDataDao dB_DeviceRealDataDao;
    private final DB_DeviceHisDataDao dB_DeviceHisDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dB_DeviceDaoConfig = daoConfigMap.get(DB_DeviceDao.class).clone();
        dB_DeviceDaoConfig.initIdentityScope(type);

        dB_HomeServerDaoConfig = daoConfigMap.get(DB_HomeServerDao.class).clone();
        dB_HomeServerDaoConfig.initIdentityScope(type);

        dB_HServerKeyDaoConfig = daoConfigMap.get(DB_HServerKeyDao.class).clone();
        dB_HServerKeyDaoConfig.initIdentityScope(type);

        dB_HServerAndUserDaoConfig = daoConfigMap.get(DB_HServerAndUserDao.class).clone();
        dB_HServerAndUserDaoConfig.initIdentityScope(type);

        dB_UserDaoConfig = daoConfigMap.get(DB_UserDao.class).clone();
        dB_UserDaoConfig.initIdentityScope(type);

        dB_HServerOnlineRecordDaoConfig = daoConfigMap.get(DB_HServerOnlineRecordDao.class).clone();
        dB_HServerOnlineRecordDaoConfig.initIdentityScope(type);

        dB_DeviceOnlineRecordDaoConfig = daoConfigMap.get(DB_DeviceOnlineRecordDao.class).clone();
        dB_DeviceOnlineRecordDaoConfig.initIdentityScope(type);

        dB_DeviceRealDataDaoConfig = daoConfigMap.get(DB_DeviceRealDataDao.class).clone();
        dB_DeviceRealDataDaoConfig.initIdentityScope(type);

        dB_DeviceHisDataDaoConfig = daoConfigMap.get(DB_DeviceHisDataDao.class).clone();
        dB_DeviceHisDataDaoConfig.initIdentityScope(type);

        dB_DeviceDao = new DB_DeviceDao(dB_DeviceDaoConfig, this);
        dB_HomeServerDao = new DB_HomeServerDao(dB_HomeServerDaoConfig, this);
        dB_HServerKeyDao = new DB_HServerKeyDao(dB_HServerKeyDaoConfig, this);
        dB_HServerAndUserDao = new DB_HServerAndUserDao(dB_HServerAndUserDaoConfig, this);
        dB_UserDao = new DB_UserDao(dB_UserDaoConfig, this);
        dB_HServerOnlineRecordDao = new DB_HServerOnlineRecordDao(dB_HServerOnlineRecordDaoConfig, this);
        dB_DeviceOnlineRecordDao = new DB_DeviceOnlineRecordDao(dB_DeviceOnlineRecordDaoConfig, this);
        dB_DeviceRealDataDao = new DB_DeviceRealDataDao(dB_DeviceRealDataDaoConfig, this);
        dB_DeviceHisDataDao = new DB_DeviceHisDataDao(dB_DeviceHisDataDaoConfig, this);

        registerDao(DB_Device.class, dB_DeviceDao);
        registerDao(DB_HomeServer.class, dB_HomeServerDao);
        registerDao(DB_HServerKey.class, dB_HServerKeyDao);
        registerDao(DB_HServerAndUser.class, dB_HServerAndUserDao);
        registerDao(DB_User.class, dB_UserDao);
        registerDao(DB_HServerOnlineRecord.class, dB_HServerOnlineRecordDao);
        registerDao(DB_DeviceOnlineRecord.class, dB_DeviceOnlineRecordDao);
        registerDao(DB_DeviceRealData.class, dB_DeviceRealDataDao);
        registerDao(DB_DeviceHisData.class, dB_DeviceHisDataDao);
    }
    
    public void clear() {
        dB_DeviceDaoConfig.getIdentityScope().clear();
        dB_HomeServerDaoConfig.getIdentityScope().clear();
        dB_HServerKeyDaoConfig.getIdentityScope().clear();
        dB_HServerAndUserDaoConfig.getIdentityScope().clear();
        dB_UserDaoConfig.getIdentityScope().clear();
        dB_HServerOnlineRecordDaoConfig.getIdentityScope().clear();
        dB_DeviceOnlineRecordDaoConfig.getIdentityScope().clear();
        dB_DeviceRealDataDaoConfig.getIdentityScope().clear();
        dB_DeviceHisDataDaoConfig.getIdentityScope().clear();
    }

    public DB_DeviceDao getDB_DeviceDao() {
        return dB_DeviceDao;
    }

    public DB_HomeServerDao getDB_HomeServerDao() {
        return dB_HomeServerDao;
    }

    public DB_HServerKeyDao getDB_HServerKeyDao() {
        return dB_HServerKeyDao;
    }

    public DB_HServerAndUserDao getDB_HServerAndUserDao() {
        return dB_HServerAndUserDao;
    }

    public DB_UserDao getDB_UserDao() {
        return dB_UserDao;
    }

    public DB_HServerOnlineRecordDao getDB_HServerOnlineRecordDao() {
        return dB_HServerOnlineRecordDao;
    }

    public DB_DeviceOnlineRecordDao getDB_DeviceOnlineRecordDao() {
        return dB_DeviceOnlineRecordDao;
    }

    public DB_DeviceRealDataDao getDB_DeviceRealDataDao() {
        return dB_DeviceRealDataDao;
    }

    public DB_DeviceHisDataDao getDB_DeviceHisDataDao() {
        return dB_DeviceHisDataDao;
    }

}
