package njsyg.greendao.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import njsyg.greendao.db.model.DB_HomeServer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB__HOME_SERVER".
*/
public class DB_HomeServerDao extends AbstractDao<DB_HomeServer, Long> {

    public static final String TABLENAME = "DB__HOME_SERVER";

    /**
     * Properties of entity DB_HomeServer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Hserver_id = new Property(0, Long.class, "hserver_id", true, "HSERVER_ID");
        public final static Property Hserver_sn = new Property(1, String.class, "hserver_sn", false, "HSERVER_SN");
        public final static Property Hserver_ip = new Property(2, String.class, "hserver_ip", false, "HSERVER_IP");
        public final static Property Hserver_nickName = new Property(3, String.class, "hserver_nickName", false, "HSERVER_NICK_NAME");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
    };


    public DB_HomeServerDao(DaoConfig config) {
        super(config);
    }
    
    public DB_HomeServerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB__HOME_SERVER\" (" + //
                "\"HSERVER_ID\" INTEGER PRIMARY KEY ," + // 0: hserver_id
                "\"HSERVER_SN\" TEXT," + // 1: hserver_sn
                "\"HSERVER_IP\" TEXT," + // 2: hserver_ip
                "\"HSERVER_NICK_NAME\" TEXT," + // 3: hserver_nickName
                "\"REMARK\" TEXT);"); // 4: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB__HOME_SERVER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DB_HomeServer entity) {
        stmt.clearBindings();
 
        Long hserver_id = entity.getHserver_id();
        if (hserver_id != null) {
            stmt.bindLong(1, hserver_id);
        }
 
        String hserver_sn = entity.getHserver_sn();
        if (hserver_sn != null) {
            stmt.bindString(2, hserver_sn);
        }
 
        String hserver_ip = entity.getHserver_ip();
        if (hserver_ip != null) {
            stmt.bindString(3, hserver_ip);
        }
 
        String hserver_nickName = entity.getHserver_nickName();
        if (hserver_nickName != null) {
            stmt.bindString(4, hserver_nickName);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DB_HomeServer entity) {
        stmt.clearBindings();
 
        Long hserver_id = entity.getHserver_id();
        if (hserver_id != null) {
            stmt.bindLong(1, hserver_id);
        }
 
        String hserver_sn = entity.getHserver_sn();
        if (hserver_sn != null) {
            stmt.bindString(2, hserver_sn);
        }
 
        String hserver_ip = entity.getHserver_ip();
        if (hserver_ip != null) {
            stmt.bindString(3, hserver_ip);
        }
 
        String hserver_nickName = entity.getHserver_nickName();
        if (hserver_nickName != null) {
            stmt.bindString(4, hserver_nickName);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DB_HomeServer readEntity(Cursor cursor, int offset) {
        DB_HomeServer entity = new DB_HomeServer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // hserver_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // hserver_sn
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hserver_ip
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hserver_nickName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // remark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DB_HomeServer entity, int offset) {
        entity.setHserver_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHserver_sn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHserver_ip(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHserver_nickName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DB_HomeServer entity, long rowId) {
        entity.setHserver_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DB_HomeServer entity) {
        if(entity != null) {
            return entity.getHserver_id();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
