package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__DEVICE_ONLINE_RECORD".
 */
@Entity
public class DB_DeviceOnlineRecord {

    @Id
    private Long id;
    private String device_sn;
    private Integer device_onlineState;
    private java.util.Date updatetime;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DB_DeviceOnlineRecord() {
    }

    public DB_DeviceOnlineRecord(Long id) {
        this.id = id;
    }

    @Generated
    public DB_DeviceOnlineRecord(Long id, String device_sn, Integer device_onlineState, java.util.Date updatetime, String remark) {
        this.id = id;
        this.device_sn = device_sn;
        this.device_onlineState = device_onlineState;
        this.updatetime = updatetime;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDevice_sn() {
        return device_sn;
    }

    public void setDevice_sn(String device_sn) {
        this.device_sn = device_sn;
    }

    public Integer getDevice_onlineState() {
        return device_onlineState;
    }

    public void setDevice_onlineState(Integer device_onlineState) {
        this.device_onlineState = device_onlineState;
    }

    public java.util.Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(java.util.Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
