package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__DEVICE_REAL_DATA".
 */
@Entity
public class DB_DeviceRealData {

    @Id
    private Long id;
    private String device_sn;
    private Integer device_state;
    private Float device_U;
    private Float device_I;
    private Float device_P;
    private Float device_electricity;
    private java.util.Date updatetime;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DB_DeviceRealData() {
    }

    public DB_DeviceRealData(Long id) {
        this.id = id;
    }

    @Generated
    public DB_DeviceRealData(Long id, String device_sn, Integer device_state, Float device_U, Float device_I, Float device_P, Float device_electricity, java.util.Date updatetime, String remark) {
        this.id = id;
        this.device_sn = device_sn;
        this.device_state = device_state;
        this.device_U = device_U;
        this.device_I = device_I;
        this.device_P = device_P;
        this.device_electricity = device_electricity;
        this.updatetime = updatetime;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDevice_sn() {
        return device_sn;
    }

    public void setDevice_sn(String device_sn) {
        this.device_sn = device_sn;
    }

    public Integer getDevice_state() {
        return device_state;
    }

    public void setDevice_state(Integer device_state) {
        this.device_state = device_state;
    }

    public Float getDevice_U() {
        return device_U;
    }

    public void setDevice_U(Float device_U) {
        this.device_U = device_U;
    }

    public Float getDevice_I() {
        return device_I;
    }

    public void setDevice_I(Float device_I) {
        this.device_I = device_I;
    }

    public Float getDevice_P() {
        return device_P;
    }

    public void setDevice_P(Float device_P) {
        this.device_P = device_P;
    }

    public Float getDevice_electricity() {
        return device_electricity;
    }

    public void setDevice_electricity(Float device_electricity) {
        this.device_electricity = device_electricity;
    }

    public java.util.Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(java.util.Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
