package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__HSERVER_AND_USER".
 */
@Entity
public class DB_HServerAndUser implements Serializable{

    private Long id;
    private String hserver_sn;
    private String hserver_ip;
    private String user_phoneNumber;
    private String hserver_nickName;
    private java.util.Date addtime;
    private Integer isdefault;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DB_HServerAndUser() {
    }

    public DB_HServerAndUser(Long id) {
        this.id = id;
    }

    public DB_HServerAndUser(Long id, String hserver_sn, String hserver_ip, String user_phoneNumber, String hserver_nickName, java.util.Date addtime, Integer isdefault, String remark) {
        this.id = id;
        this.hserver_sn = hserver_sn;
        this.hserver_ip = hserver_ip;
        this.user_phoneNumber = user_phoneNumber;
        this.hserver_nickName = hserver_nickName;
        this.addtime = addtime;
        this.isdefault = isdefault;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHserver_sn() {
        return hserver_sn;
    }

    public void setHserver_sn(String hserver_sn) {
        this.hserver_sn = hserver_sn;
    }

    public String getHserver_ip() {
        return hserver_ip;
    }

    public void setHserver_ip(String hserver_ip) {
        this.hserver_ip = hserver_ip;
    }

    public String getUser_phoneNumber() {
        return user_phoneNumber;
    }

    public void setUser_phoneNumber(String user_phoneNumber) {
        this.user_phoneNumber = user_phoneNumber;
    }

    public String getHserver_nickName() {
        return hserver_nickName;
    }

    public void setHserver_nickName(String hserver_nickName) {
        this.hserver_nickName = hserver_nickName;
    }

    public java.util.Date getAddtime() {
        return addtime;
    }

    public void setAddtime(java.util.Date addtime) {
        this.addtime = addtime;
    }

    public Integer getIsdefault() {
        return isdefault;
    }

    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
