package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__HOME_SERVER".
 */
@Entity
public class DB_HomeServer implements Serializable{

    @Id
    private Long hserver_id;
    private String hserver_sn;
    private String hserver_ip;
    private String hserver_nickName;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DB_HomeServer() {
    }

    public DB_HomeServer(Long hserver_id) {
        this.hserver_id = hserver_id;
    }

    @Generated
    public DB_HomeServer(Long hserver_id, String hserver_sn, String hserver_ip, String hserver_nickName, String remark) {
        this.hserver_id = hserver_id;
        this.hserver_sn = hserver_sn;
        this.hserver_ip = hserver_ip;
        this.hserver_nickName = hserver_nickName;
        this.remark = remark;
    }

    public Long getHserver_id() {
        return hserver_id;
    }

    public void setHserver_id(Long hserver_id) {
        this.hserver_id = hserver_id;
    }

    public String getHserver_sn() {
        return hserver_sn;
    }

    public void setHserver_sn(String hserver_sn) {
        this.hserver_sn = hserver_sn;
    }

    public String getHserver_ip() {
        return hserver_ip;
    }

    public void setHserver_ip(String hserver_ip) {
        this.hserver_ip = hserver_ip;
    }

    public String getHserver_nickName() {
        return hserver_nickName;
    }

    public void setHserver_nickName(String hserver_nickName) {
        this.hserver_nickName = hserver_nickName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
