package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__HSERVER_KEY".
 */
@Entity
public class DB_HServerKey implements Serializable{

    @Id
    private Long id;
    private String hserver_sn;
    private Integer keytype;
    private String keyvalue;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DB_HServerKey() {
    }

    public DB_HServerKey(Long id) {
        this.id = id;
    }

    @Generated
    public DB_HServerKey(Long id, String hserver_sn, Integer keytype, String keyvalue, String remark) {
        this.id = id;
        this.hserver_sn = hserver_sn;
        this.keytype = keytype;
        this.keyvalue = keyvalue;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHserver_sn() {
        return hserver_sn;
    }

    public void setHserver_sn(String hserver_sn) {
        this.hserver_sn = hserver_sn;
    }

    public Integer getKeytype() {
        return keytype;
    }

    public void setKeytype(Integer keytype) {
        this.keytype = keytype;
    }

    public String getKeyvalue() {
        return keyvalue;
    }

    public void setKeyvalue(String keyvalue) {
        this.keyvalue = keyvalue;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
