package njsyg.greendao.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB__USER".
 */
@Entity
public class DB_User {

    @Id
    private Long user_id;
    private String user_phoneNumber;
    private String user_nickName;
    private String user_pwd;
    private String user_email;
    private String user_headImg;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DB_User() {
    }

    public DB_User(Long user_id) {
        this.user_id = user_id;
    }

    @Generated
    public DB_User(Long user_id, String user_phoneNumber, String user_nickName, String user_pwd, String user_email, String user_headImg, String remark) {
        this.user_id = user_id;
        this.user_phoneNumber = user_phoneNumber;
        this.user_nickName = user_nickName;
        this.user_pwd = user_pwd;
        this.user_email = user_email;
        this.user_headImg = user_headImg;
        this.remark = remark;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public String getUser_phoneNumber() {
        return user_phoneNumber;
    }

    public void setUser_phoneNumber(String user_phoneNumber) {
        this.user_phoneNumber = user_phoneNumber;
    }

    public String getUser_nickName() {
        return user_nickName;
    }

    public void setUser_nickName(String user_nickName) {
        this.user_nickName = user_nickName;
    }

    public String getUser_pwd() {
        return user_pwd;
    }

    public void setUser_pwd(String user_pwd) {
        this.user_pwd = user_pwd;
    }

    public String getUser_email() {
        return user_email;
    }

    public void setUser_email(String user_email) {
        this.user_email = user_email;
    }

    public String getUser_headImg() {
        return user_headImg;
    }

    public void setUser_headImg(String user_headImg) {
        this.user_headImg = user_headImg;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
